services:
  app:
    build: .
    container_name: api
    ports:
      - "6969:6969"
    volumes:
      - .:/app
      - /app/node_modules
    command: bun run dev
  db:
    image: postgres
    container_name: db
    restart: always
    enviroment:
      POSTGRES_USER: ssts
      POSTGRES_PASSWORD: ssts
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
